include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - file_names
    - omit_local_variable_types
    - prefer_final_locals
    - prefer_relative_imports
    - prefer_single_quotes
    - sort_child_properties_last
    - sort_constructors_first
    - type_annotate_public_apis
    - unawaited_futures
    - flutter_style_todos
