name: joyato
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  firebase_analytics: ^9.3.0
  firebase_auth: ^3.6.1
  google_sign_in: ^5.4.0
  google_maps_flutter: ^2.1.10
  flutter_riverpod: ^1.0.4
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0
  cloud_firestore: ^3.4.4
  geoflutterfire:
    git:
      url: https://github.com/samuraituru/GeoFlutterFire.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.3
  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

assets:
  - assets/images

flutter_icons:
  android: true
  ios: true
